// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Automatically tags call transcripts with categories like 'complaint' or 'urgent'.
 *
 * - autoTagCall - A function that handles the auto-tagging process.
 * - AutoTagCallInput - The input type for the autoTagCall function.
 * - AutoTagCallOutput - The return type for the autoTagCall function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AutoTagCallInputSchema = z.object({
  transcript: z.string().describe('The transcript of the call.'),
});
export type AutoTagCallInput = z.infer<typeof AutoTagCallInputSchema>;

const AutoTagCallOutputSchema = z.object({
  tags: z
    .array(z.enum(['complaint', 'urgent', 'query', 'order', 'other']))
    .describe('The tags for the call transcript.'),
  urgencyLevel: z
    .string()
    .describe('The urgency level of the call (high, medium, low).'),
});
export type AutoTagCallOutput = z.infer<typeof AutoTagCallOutputSchema>;

export async function autoTagCall(input: AutoTagCallInput): Promise<AutoTagCallOutput> {
  return autoTagCallFlow(input);
}

const prompt = ai.definePrompt({
  name: 'autoTagCallPrompt',
  input: {schema: AutoTagCallInputSchema},
  output: {schema: AutoTagCallOutputSchema},
  prompt: `You are an AI assistant that analyzes call transcripts and automatically tags them with relevant categories.

  Analyze the following call transcript and identify any complaints, urgent issues, queries, or orders.
  Assign tags based on the content of the transcript.
  Also, determine the urgency level of the call (high, medium, low).

  Transcript: {{{transcript}}}

  Output the tags and urgency level in JSON format.
  `, // Removed Handlebars await expression
});

const autoTagCallFlow = ai.defineFlow(
  {
    name: 'autoTagCallFlow',
    inputSchema: AutoTagCallInputSchema,
    outputSchema: AutoTagCallOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
